config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cars, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:create, :new]
  end

  resources :bookings, only: [:edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  get 'dashboard', to: 'bookings#dashboard', as: :dashboard
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  has_many :reviews, dependent: :destroy

  validates :user_id, presence: true
  validates :car_id, presence: true
  validates :date_from, presence: true
  validates :date_to, presence: true
  validates :price, presence: true

  # validate :date_from_cannot_be_in_the_past
  # validate :date_to_cannot_be_before_date_from

  private

  def date_from_cannot_be_in_the_past
    errors.add(:date_from, "can't be in the past") if date_from < Date.today
  end

  def date_to_cannot_be_before_date_from
    errors.add(:date_to, "can't be before date_from") if date_to < date_from
  end
end

app/models/car.rb
class Car < ApplicationRecord
  include PgSearch
  belongs_to :car_type
  belongs_to :user, optional: true
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  validates :brand, presence: true
  validates :model, presence: true
  validates :year, presence: true
  validates :passengers, presence: true
  validates :fuel_type, presence: true, inclusion: { in: %w[diesel petrol electric hybrid gas] }
  validates :price_per_day, presence: true
  validates :city, presence: true
  # validates :zipcode, presence: true
  validates :country, presence: true
  validates :car_type_id, presence: true
  validates :address, presence: true
  validates :photo, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  pg_search_scope :search_by_city_brand_model,
    against: [:city, :brand, :model],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/car_type.rb
class CarType < ApplicationRecord
  has_many :cars

  validates :car_type, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  has_one :user, through: :bookings
  belongs_to :booking
  validates :content, length: { maximum: 500 }
  validates :rating, presence: true, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:edit, :update, :new]

  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
    @booking.price = (@booking.date_to - @booking.date_from).to_i * @car.price_per_day
    if @booking.save
      redirect_to dashboard_path(current_user)
    else
      render "cars#show"
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to dashboard_path(current_user)
  end

  def dashboard
    @bookings = Booking.where(user_id: current_user)
    @reviews = Review.where(booking_id: @bookings)
    @cars = Car.where(user_id: current_user)
    # This is a function to get the total profit
    @number_of_days = 1
    @total_profit = 0
    @bookings.each do |booking|
      @total_profit = @total_profit + booking.price
      @number_of_days = (booking.date_to - booking.date_from).to_i
    end
    @number_of_reviews = 0
    @reviews.each do |review|
      @number_of_reviews += 1
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    respond_to do |format|
      format.html {redirect_to dashboard_path}
      format.json { head :no_content }
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :car_id, :date_from, :date_to)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :new, :create]

  layout "map", only: [:index]

  def index
    if params["query"].present?
      @cars = Car.search_by_city_brand_model(params["query"])
      @markers = @cars.map do |car|
        {
          lng: car.longitude,
          lat: car.latitude,
          id: car.id,
          infoWindow: { content: render_to_string(partial: "/cars/map_window", locals: { car: car }) }
        }
      end
    else
      @cars = Car.all
      @markers = @cars.map do |car|
        {
          lng: car.longitude,
          lat: car.latitude,
          id: car.id,
          infoWindow: { content: render_to_string(partial: "/cars/map_window", locals: { car: car }) }
        }
      end
    end
  end

  def show
    @car = Car.find(params[:id])
    @reviews = @car.reviews
    @booking = Booking.new
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save # results in true or false
      redirect_to @car
    else
      render :new
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to dashboard_path
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :year, :passengers, :price_per_day, :address, :fuel_type, :city,
                                :country, :car_type_id, :zipcode, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: :home

  def home
    @cars = Car.all

    @car1 = @cars.sample
    @car2 = @cars.sample
    @car3 = @cars.sample
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = Booking.find(params[:booking_id])
    if @review.save
      redirect_to dashboard_path(created: true)
    else
      redirect_to new_booking_review_path
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    if @review.update(review_params)
      redirect_to dashboard_path(created: true)
    else
      redirect_to edit_booking_review_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/dashboard.html.erb
<div class="wrapper">
  <div class="container">
    <!-- This shows ongoing bookings -->
    <div class="row">
      <div class="dash-square portfolio portfolio-vals">
        <div class="car-card-title">
          <div class="green-line"></div>
          <h3 class="title-show">Ongoing Bookings</h3>
        </div>
        <div class="product">
          <div class='product-body bookings-list'>
            <h3></h3>
          </div>
          <ul class="list-inline product-controls cards-list-dashboard bookings-dashboard">
            <li>Price</li>
            <li>Dates</li>
            <li id="bookings-buttons-column" style="width: 410px";>  </li>
          </ul>
        </div>
        <% nr_bookings_ongoing = 0 %>
        <% @bookings.each do |booking| %>
          <% if booking.date_to > Date.today %>
            <% nr_bookings_ongoing = nr_bookings_ongoing + 1 %>
            <div class="product product-list">
              <div class='product-body bookings-list list-inline'>
                <h3>
                  <%= link_to car_path(booking.car) do %>
                    <%= booking.car.brand %> <%= booking.car.model %>
                  <% end %>
                </h3>
              </div>
              <ul class="list-inline product-controls cards-list-dashboard bookings-dashboard">
                <li><%= booking.price.to_i %>€</li>
                <li style= "width: 90%;"><%= Date::MONTHNAMES[booking.date_to.month] %> <%= booking.date_from.day %>, <%= booking.date_from.year %> to <%= Date::MONTHNAMES[booking.date_to.month] %> <%= booking.date_to.day %></li>
                <li id="bookings-buttons-column">
                  <div class="booking-button">
                    <%= link_to "Edit", edit_booking_path(booking.id), class: "btn btn-edit" %>
                  </div>
                  <div class="booking-button">
                  <%= form_tag booking_path(booking), method: :delete do |f| %>
                  <%= submit_tag "Delete", class: "btn delete-btn sweet-alert-demo" %>
                  <% end %>
                </div>
                </li>
              </ul>
            </div>
          <% end %>
        <% end %>
        <!-- This puts a text if user doesn't have bookings ongoing -->
        <% if nr_bookings_ongoing == 0 %>
         <h4 class="text-center">You have no Bookings ongoing!</h4>
        <% end %>
      </div>
      <!-- This shows total profit and media rating -->
      <div class="dash-square portfolio portfolio-stats">
        <div class="car-card-title">
          <div class="green-line"></div>
            <h3 class="title-show">Profit/Rating</h3>
        </div>
        <div class="ratings-dashboard">
          <div class="profit-group">
            <% if @total_profit == 0 %>
              <h4 class="text-center">You have no profit yet!</h4>
            <% else %>
              <i style="font-size: 41px;color: #60CD44;" class="fas fa-money-bill-alt"></i>
              <!-- <p>500€</p> -->
              <!-- This next line separates de number with dotes -->
              <p><%= number_with_precision(@total_profit, :precision => 1, :delimiter => ',') %>€</p>
            <% end %>
          </div>
          <% rating = 0 %>
          <% number_ratings = 0 %>
          <% @reviews.each do |review| %>
            <% rating = rating + review.rating.to_f %>
            <% number_ratings += 1 %>
          <% end %>
          <!-- This puts a text if user doesn't have ratings -->
          <% if number_ratings == 0 %>
            <h4>You have no ratings, yet!</h4>
          <% else %>
            <div class="rating-group">
              <i style="font-size: 41px;color: #60CD44;" class="fas fa-star"></i>
              <p><%= (rating / number_ratings).round() %>/5</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <!-- This will show cars owned by the user -->
    <div class="row">
      <div class="dash-square my-portfolio">
        <div class="car-card-title">
          <div class="green-line"></div>
          <h3 class="title-show">Your Cars
          <%#= link_to "Add Car", new_car_path(current_user), class: "btn btn-add" %>
          <%= link_to new_car_path(current_user) do %>
            <i class="far fa-plus-square icon-add-cars"></i>
          <% end %>
        </div>
        <div class="product">
          <div class='product-body'>
            <h3> </h3>
          </div>
          <ul class="list-inline product-controls">
            <li>Nº Bookings</li>
            <li>Price per day</li>
            <li>Profit per car</li>
            <li id="bookings-buttons-column" style="width: 410px";>  </li>
          </ul>
        </div>
        <% @number_cars = 0 %>
        <% @cars.each do |car| %>
        <% @number_cars += 1 %>
          <div class="product product-list">
            <div class='list-inline product-body'>
              <li><%= car.brand %> <%= car.model %></li>
            </div>
            <ul class="list-inline product-controls">
              <li><%= car.bookings.all.length %></li>
              <li><%= car.price_per_day.to_i %>€</li>
              <li><%= @number_of_days * car.price_per_day.to_i %>€</li>
              <li id="bookings-buttons-column">
                  <div class="booking-button">
                    <%= link_to "Delete", car_path(car), method: :delete, data: { confirm: "are you sure?" }, class: "btn delete-btn" %>
                  </div>
                </li>
            </ul>
          </div>
        <% end %>
        <!-- This puts a text if user doesn't have cars -->
        <% if @number_cars == 0 %>
          <h4 class= "text-center">You have no cars to lend</h4>
        <% end %>
      </div>
    </div>
    <!-- This will show past bookings -->
    <div class="row">
      <div class="dash-square my-portfolio">
        <div class="car-card-title">
          <div class="green-line"></div>
          <h3 class="title-show">Past Bookings</h3>
        </div>
        <div class="product">
          <div class='product-body bookings-list'>
            <h3></h3>
          </div>
          <ul class="list-inline product-controls cards-list-dashboard bookings-dashboard">
            <li style="width: 80%;">Price</li>
            <li style="width: 67%;">Dates</li>
            <li id="bookings-buttons-column" style="width: 410px";>  </li>
          </ul>
        </div>
        <% nr_bookings_past = 0 %>
        <% @bookings.each do |booking| %>
          <% if booking.date_to < Date.today %>
            <% nr_bookings_past += 1 %>
            <div class="product product-list">
              <div class='list-inline product-body'>
                <li><%= booking.car.brand %> <%= booking.car.model %></li>
              </div>
              <ul class="list-inline product-controls">
                <li><%= booking.price.to_i %>€</li>
                <li style="width: 200%;"><%= Date::MONTHNAMES[booking.date_to.month] %> <%= booking.date_from.day %>, <%= booking.date_from.year %> to <%= Date::MONTHNAMES[booking.date_to.month] %> <%= booking.date_to.day %></li>
                <li id="bookings-buttons-column">
                  <div class="booking-button add-review-button-past">
                    <% if @number_of_reviews >= 0 %>
                      <%= link_to "Add Review", new_booking_review_path(booking.id), class: "btn btn-add-review" %>
                    <% end %>
                  </div>
                </li>
              </ul>
            </div>
          <% end %>
          <% end %>
          <!-- This puts a text if user doesn't have bookings completed -->
          <% if nr_bookings_past == 0 %>
            <h4 class="text-center">You have no Bookings completed!</h4>
        <% end %>
      </div>
     <!--  <div class="dash-square top-win-lose">

      </div>
      <div class="dash-square twitter-feed">

      </div>
      <div class="dash-square top-traded">

      </div> -->
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="booking-form">
  <%= simple_form_for [@car, @booking] do |f| %>
  <div class="form-inline text-center"><%= f.input :date_from, as: :string, input_html: { class: 'special' }%></div>
  <div class="form-inline text-center"><%= f.input :date_to, as: :string%></div>
  <% f.hidden_field :title, value: "some value" %>
  <h4 class= "text-center">Price:</h4><h4 id= "rent-price"><strong></strong></h4>
  <div class="rent-button"><%= f.button :submit, "Change Booking", class: "btn btn-primary show-button" %></div>
  <% end %>
</div>

app/views/cars/_map_window.html.erb
<div class="container-marker">
  <div>
    <%= image_tag car.photo, class:"marker-photo" %>
  </div>
</div>


<div class="container-marker-details">
  <div class="brand-model">
    <h1><%= car.brand %></h3>
    <h2><%= car.model %></h3>
  </div>
  <div class="brand-model">
    <h1><%= car.fuel_type.capitalize %></h3>
    <h2><%= car.horsepower %> HP</h3>
  </div>
  <div class="price">
    <h1><%= car.price_per_day.to_i %></h1>
    <h2>EUR</h2>
  </div>
</div>

<%= link_to car_path(car), target: "_blank" do %>
  <h3 id="button-marker" class="btn btn-success">Book Now</h3>
<% end %>

app/views/cars/index.html.erb
  <div class="search-container">
    <%= form_tag cars_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
        placeholder: "Enter a city, brand and/or model"
        %>
        <%= button_tag "Find Cars", class: "btn btn-success my-btn", style: "display: none;" %>
        <% end %>
  </div>
<div class="cars-wrapper">
    <div class="cars-container">
      <% @cars.each do |car| %>
      <div id="car-<%=car.id%>"class="product">
        <%= image_tag car.photo, class: "index-product-image hidden-xs" %>
        <div class='product-body'>
          <h3><%= link_to car.brand, car_path(car), target: "_blank" %></h3>
          <p><%= link_to car.model, car_path(car), target: "_blank" %></p>
          <li class="list-group-item">
            <small>
              <% count = 0 %>
                <% rating = rand(2..5) %>
              <% 5.times do %>
                <% if rating > count %>
                  <i class="fas fa-star"></i>
                <% else %>
                  <i class="far fa-star"></i>
                <% end %>
                <% count += 1 %>
              <% end %>
            </small>
          </li>
        </div>
        <ul class="hidden-sm hidden-xs">
          <li><%= link_to "#{car.price_per_day.to_i}€ per day", car_path(car), target: "_blank" %></li>
          <li><%= link_to car.city, car_path(car), target: "_blank" %></li>
          <li><%= link_to car.country, car_path(car), target: "_blank" %></li>
        </ul>
      </div>
      <% end %>
    </div>
    <div class="map-container">
     <div
     id="map"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
     ></div>
   </div>
</div>

app/views/cars/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col sm offset-4">
    <%= simple_form_for @car do |f| %>
      <div class="form-row">
        <div class="left-form">
          <%= f.input :brand %>
        </div>
        <div class="right-form">
          <%= f.input :model%>
        </div>
      </div>
      <div class="form-row">
        <div class="left-form">
          <%= f.input :year %>
        </div>
        <div class="right-form">
          <%= f.input :fuel_type, collection: %w[ diesel petrol electric hybrid gas ] %>
        </div>
      </div>
      <div class="form-row">
        <div class="left-form">
          <%= f.input :color %>
        </div>
        <div class="right-form">
          <%= f.association :car_type, label_method: :car_type, value_method: :id%>
        </div>
      </div>

      <div class="form-row">
        <div class="left-form">
          <%= f.input :passengers %>
        </div>
        <div class="right-form">
          <%= f.input :horsepower %>
        </div>
      </div>
      <div class="form-row">
        <div class="left-form">
          <%= f.input :price_per_day %>
        </div>
        <div class="right-form">
          <%= f.input :photo, placeholder: "Paste an URL of your photo" %>
        </div>
      </div>
      <div class="form-row">
        <div class="left-form">
          <%= f.input :city %>
        </div>
        <div class="right-form">
          <%= f.input :zipcode %>
        </div>
      </div>
      <div class="form-row row-address">
          <%= f.input :address %>
      </div>
      <%= f.country_select :country %>
      <%#= f.input :address %>
      <div class="form-submit">
        <%= f.button :submit, class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Wheels.com - Find your perfect car today</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body>
    <!-- Flash messages copied as placeholder -->
    <!--  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= render "shared/navbar-wheels" %>
    <%= yield %>
    <%= render "shared/footer"  %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Wheels.com - Find your perfect car today</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= stylesheet_pack_tag "map" %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body>
    <!-- Flash messages copied as placeholder -->
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= render "shared/navbar-wheels" unless devise_controller? %>
    <%= yield %>
    <%= render "shared/footer"  %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="background">
  <div class="banner">
    <div class="banner-content">
      <h1 style="text-shadow: 2px 2px rgb(0,0,0,0.4);">Find your perfect car today...</h1>
      <%= form_tag cars_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
        placeholder: "Enter a city"
        %>
        <%= button_tag "Find Cars", class: "btn btn-success my-btn" %>
        <% end %>
      <!-- <form action="/cars" class="form-inline">
        <input type="text" class="form-control input-lg" placeholder="Enter a city">
        <input type="submit" class="btn btn-success btn-lg" value="Search">
      </form> -->
    </div>
  </div>
</div>

<div class="container icons-container">
  <div class="icon-cards">
    <div class="text-center icon-cards-title">
      <h2>Who We Are</h2>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <div class="card text-center">
          <i class="fas fa-globe-americas fa-3x"></i>
          <p>Rent a Car Anywhere</p>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="card text-center">
          <i class="fas fa-car fa-3x"></i>
          <p>Loan your Car</p>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="card text-center">
          <i class="fas fa-money-bill-alt fa-3x"></i>
          <p>Earn Passive Income</p>
        </div>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="container lp-container">
  <h2>Our latest offers</h2>
  <div class="row">

    <% @cars.sample(3).each do |car| %>
    <div class="col-xs-12 col-sm-6">
      <div class="landing-card">
        <div class="card-picture">
          <div class="lp-product-image hidden-xs" style="background-image: url(<%= image_url car.photo %>);">
          </div>
        </div>
        <div class='lp-car-info text-center'>
          <div class="left-info">
            <h3><%= link_to car.brand, car_path(car) %></h3>
            <p><%= link_to car.model, car_path(car) %></p>
            <li class="list-group-item">
              <small>
                <% count = 0 %>
                <% rating = rand(2..5) %>
                <% 5.times do %>
                <% if rating > count %>
                <i class="fas fa-star"></i>
                <% else %>
                <i class="far fa-star"></i>
                <% end %>
                <% count += 1 %>
                <% end %>
              </small>
            </li>
          </div>
          <div class="right-info">
           <ul class="list-group">
            <li class="list-group-item"><%= link_to "#{car.price_per_day.to_i}€ per day", car_path(car) %></li>
            <li class="list-group-item"><%= link_to car.city, car_path(car) %></li>
            <li class="list-group-item"><%= link_to car.country, car_path(car) %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% end %>

</div>
</div>

app/views/reviews/edit.html.erb
<h2> Hello this is reviews update </h2>


<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :title %>
  <%= f.input :content  %>
  <%= f.input :rating  %>
  <%= f.submit "Update the Review", class: "btn btn-success" %>
<% end %>

app/views/reviews/new.html.erb
<!-- Form to require params for review.  Permissions: Title content and rating -->
<div class="row">
  <div class="col-xs-12 col-sm-6 col sm offset-4">
    <%= simple_form_for [@booking, @review] do |f| %>
      <div class="form-row form-row-last">
        <%= f.input :title %>
      </div>
      <div class="form-row form-row-last">
        <%= f.input :content, placeholder: "Maximum 500 characters" %>
      </div>
      <div class="form-row form-row-last">
          <%= f.input :rating, placeholder: "From 1 to 5"  %>
      </div>
      <div class="form-submit">
        <%= f.submit "Add a review", id: "sweet-alert-demo", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar-wheels-lp.html.erb
<div class="navbar-croker">
  <div class="content-container">
    <a href="/">
      <%= image_tag "logo2.png", alt: "logo", class: "logo" %>
    </a>
    <div class="tabs-button-container">
      <div class="navbar-tabs">
        <%= link_to 'Cars', cars_path %>
        <%= link_to 'Dashboard', dashboard_path %>
      </div>
      <div class="right-content">
        <% if current_user.nil? %>
        <%# else  %>
          <%= link_to "Sign Up", new_user_registration_path, class: "sign-out-btn" %>
          <%= link_to "Log In", new_user_session_path, method: :get %>
        <% end %>
        <!-- <i class="fas fa-ellipsis-v"></i> -->
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar-wheels.html.erb
<div class="navbar-croker">
  <div class="content-container">
    <a href="/">
      <%= image_tag "logo2.png", alt: "logo", class: "logo" %>
    </a>
    <div class="tabs-button-container">
      <div class="navbar-tabs">
        <% if controller.class == CarsController && controller.action_name == 'index' %>
        <%= link_to 'Cars', cars_path, class: "active"  %>
        <% else %>
        <%= link_to 'Cars', cars_path  %>
        <% end %>
        <% if controller.class == BookingsController && controller.action_name == 'dashboard' %>
        <%= link_to 'Dashboard', dashboard_path, class: "active" %>
        <% else %>
        <%= link_to 'Dashboard', dashboard_path %>
        <% end %>
      </div>
    </div>
    <div class="right-content">
      <% if current_user.nil? %>
      <%= link_to "Sign Up", new_user_registration_path, class: "sign-up my-btn", style: "border: 3px solid #60CD44; background-color: white; color: #60CD44;" %>
      <%= link_to "Log In", new_user_session_path, method: :get, class: "log-in my-btn", style: "border: 3px solid #60CD44; color: white;" %>
      <% else  %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "sign-out my-btn", style: "border: 3px solid rgb(200,200,200); color: rgb(200,200,200); background-color: white" %>
      <% end %>
      <!-- <i class="fas fa-ellipsis-v"></i> -->
    </div>
  </div>
</div>